// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygtrsltvuelkvdmuqbop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndHJzbHR2dWVsa3ZkbXVxYm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTY0NzEsImV4cCI6MjA2MTE3MjQ3MX0._1F5Yw5pYeATFFW7WKstWfwP8_M2whkpBmI2qat3Ln4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);